# Generated by Django 3.2.8 on 2021-10-26 05:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.CharField(blank=True, max_length=150, null=True)),
                ('host', models.URLField(blank=True, null=True)),
                ('displayName', models.CharField(max_length=100, unique=True)),
                ('github', models.URLField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('postId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=100)),
                ('source', models.URLField(blank=True, null=True)),
                ('origin', models.URLField(blank=True, null=True)),
                ('description', models.TextField(default='')),
                ('contentType', models.CharField(default='text/plain', max_length=20)),
                ('categories', models.TextField(default='')),
                ('commentCount', models.IntegerField(default=0)),
                ('commentUrl', models.TextField()),
                ('publishedOn', models.DateTimeField(default=django.utils.timezone.now)),
                ('visibility', models.CharField(max_length=20)),
                ('unlisted', models.BooleanField(default=False)),
                ('authorId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.author')),
            ],
        ),
    ]
