# Generated by Django 3.2.9 on 2021-11-25 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='http_password',
            field=models.CharField(blank=True, default='', max_length=512, null=True, verbose_name='Http Auth Password(FETCH)'),
        ),
        migrations.AlterField(
            model_name='node',
            name='create_time',
            field=models.FloatField(default=1637835926.113363, verbose_name='Node create timestamp'),
        ),
    ]
