# Generated by Django 3.2.9 on 2021-11-23 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='password_md5',
            field=models.CharField(default='123', max_length=32, verbose_name='Auth Password'),
            preserve_default=False,
        ),
    ]
