# Generated by Django 3.2.9 on 2021-12-05 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='if_foreign',
            field=models.BooleanField(default=False),
        ),
    ]
