# Generated by Django 3.2.9 on 2021-12-04 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='profilePic',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
