# Generated by Django 3.2.9 on 2021-11-25 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20211125_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='remoteId',
            field=models.CharField(blank=True, default='', max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='node',
            name='create_time',
            field=models.FloatField(default=1637841332.644908, verbose_name='Node create timestamp'),
        ),
    ]
