# Generated by Django 3.2.9 on 2021-12-06 12:44

from django.db import migrations, models
import main.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_author_if_foreign'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('file_path', models.FilePathField(path=main.models.get_path)),
            ],
        ),
    ]
