# Generated by Django 3.2.8 on 2021-10-26 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='author',
            new_name='authorId',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='postId',
        ),
    ]
