# Generated by Django 3.2.9 on 2021-11-23 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_node_password_md5'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='node_type',
            field=models.CharField(choices=[('SHARE', 'Share'), ('FETCH', 'Fetch')], default='SHARE', max_length=5, verbose_name='Node Type'),
            preserve_default=False,
        ),
    ]
