# Generated by Django 3.2.9 on 2021-12-06 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_buddyrequest_friendrequest'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FriendNotification',
            new_name='FollowNotification',
        ),
    ]
