# Generated by Django 3.2.9 on 2021-12-06 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_postnotification_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postnotification',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterUniqueTogether(
            name='postnotification',
            unique_together=set(),
        ),
    ]
