# Generated by Django 3.2.9 on 2021-12-06 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_author_if_foreign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='visibility',
            field=models.CharField(choices=[('public', 'PUBLIC'), ('friends', 'FRIENDS ONLY'), ('toAuthor', 'AUTHOR ONLY')], default='public', max_length=20),
        ),
    ]
