# Generated by Django 3.2.9 on 2021-12-03 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_notification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='authorId',
            new_name='userId',
        ),
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.CharField(default='like', max_length=20),
        ),
    ]
