# Generated by Django 3.2.9 on 2021-12-06 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20211206_0653'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='follownotification',
            unique_together=set(),
        ),
    ]
