# Generated by Django 3.2.8 on 2021-10-26 19:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20211026_1749'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='commentUrl',
            field=models.TextField(default=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
        ),
        migrations.AlterField(
            model_name='post',
            name='visibility',
            field=models.CharField(default='PUBLIC', max_length=20),
        ),
    ]
