# Generated by Django 3.2.9 on 2021-12-06 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_friendnotification_follownotification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follownotification',
            old_name='authorId',
            new_name='followeeId',
        ),
    ]
