# Generated by Django 3.2.9 on 2021-12-06 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_mediafile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='profilePic',
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
