# Generated by Django 3.2.9 on 2021-11-23 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_node_node_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='http_username',
            field=models.CharField(blank=True, default='', max_length=512, null=True, verbose_name='Http Auth Username(FETCH)'),
        ),
        migrations.AlterField(
            model_name='post',
            name='contentType',
            field=models.CharField(choices=[('text/markdown', 'Common Mark'), ('text/plain', 'Utf-8'), ('application/base64', 'application/base64'), ('image/png;base64', 'PNG'), ('image/jpeg;base64', 'JPEG')], default='text/plain', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='visibility',
            field=models.CharField(choices=[('public', 'PUBLIC'), ('friends', 'FRIENDS ONLY'), ('fof', 'FRIENDS OF FRIENDS'), ('toAuthor', 'AUTHOR ONLY')], default='public', max_length=20),
        ),
    ]
