# Generated by Django 3.2.9 on 2021-12-06 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_post_visibility'),
        ('main', '0004_alter_author_profilepic'),
    ]

    operations = [
    ]
