# Generated by Django 3.2.9 on 2021-12-06 02:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_authorid_follownotification_followeeid'),
    ]

    operations = [
        migrations.AddField(
            model_name='postnotification',
            name='senderId',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='sent_from_senderId', to='main.author'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='postnotification',
            name='authorId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_to_authorID', to='main.author'),
        ),
        migrations.AlterUniqueTogether(
            name='postnotification',
            unique_together={('authorId', 'senderId')},
        ),
    ]
