# Generated by Django 3.2.9 on 2021-11-26 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_node_create_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='create_time',
            field=models.FloatField(default=1637902468.3367105, verbose_name='Node create timestamp'),
        ),
    ]
