# Generated by Django 3.2.9 on 2021-12-06 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_follownotification_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='following',
            unique_together=set(),
        ),
    ]
