# Generated by Django 3.2.9 on 2021-12-03 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_notification_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='userId',
            new_name='authorId',
        ),
    ]
