# Generated by Django 3.2.9 on 2021-11-26 08:56

from django.db import migrations, models
import time


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_node_create_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='fetch_author_url',
            field=models.CharField(blank=True, default='', max_length=512, null=True, verbose_name='Author URL(FETCH)'),
        ),
        migrations.AddField(
            model_name='node',
            name='fetch_post_url',
            field=models.CharField(blank=True, default='', max_length=512, null=True, verbose_name='Post URL(FETCH)'),
        ),
        migrations.AlterField(
            model_name='node',
            name='create_time',
            field=models.FloatField(default=time.time, verbose_name='Node create timestamp'),
        ),
    ]
