# Generated by Django 3.2.9 on 2021-12-06 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_merge_20211206_1730'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='following',
            unique_together=set(),
        ),
        migrations.DeleteModel(
            name='FriendRequest',
        ),
    ]
