# Generated by Django 3.2.8 on 2021-10-27 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20211026_2046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='contentType',
        ),
        migrations.AddField(
            model_name='comment',
            name='text',
            field=models.TextField(default='', max_length=500),
        ),
    ]
