# Generated by Django 3.2.9 on 2021-12-06 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20211206_0232'),
    ]

    operations = [
        migrations.AddField(
            model_name='postnotification',
            name='comment_text',
            field=models.CharField(default='', max_length=120),
        ),
    ]
