# Generated by Django 3.2.9 on 2021-12-03 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_userid_notification_authorid'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='sender_display_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
