# Generated by Django 3.2.9 on 2021-12-06 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_postnotification_comment_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='follownotification',
            name='authorId',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='follow_to_authorID', to='main.author'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='follownotification',
            name='senderId',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='follow_by_senderId', to='main.author'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='follownotification',
            unique_together={('authorId', 'senderId')},
        ),
        migrations.RemoveField(
            model_name='follownotification',
            name='followeeId',
        ),
    ]
