# Generated by Django 3.2.9 on 2021-11-26 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20211126_0856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='displayName',
            field=models.CharField(default='', max_length=100),
        ),
    ]
