# Generated by Django 3.2.8 on 2021-10-27 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20211027_0104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='description',
        ),
        migrations.AddField(
            model_name='post',
            name='post_text',
            field=models.TextField(default=''),
        ),
    ]
