# Generated by Django 3.2.9 on 2021-12-03 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_notification_sender_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='front_end_text',
            field=models.CharField(default='', max_length=120),
        ),
    ]
