# Generated by Django 3.2.9 on 2021-11-28 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_author_displayname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='commentUrl',
            field=models.CharField(default='https://cmput404f21t17.herokuapp.com/service/post/<django.db.models.fields.UUIDField>/comments/', max_length=512),
        ),
    ]
