# Generated by Django 3.2.9 on 2021-12-04 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_notification_front_end_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='time',
            new_name='publishedOn',
        ),
    ]
