# Generated by Django 3.2.9 on 2021-12-04 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_rename_time_notification_publishedon'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Notification',
            new_name='PostNotification',
        ),
        migrations.CreateModel(
            name='FriendNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('front_end_text', models.CharField(default='', max_length=120)),
                ('sentOn', models.DateTimeField(auto_now_add=True)),
                ('sender_display_name', models.CharField(default='', max_length=100)),
                ('authorId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.author')),
            ],
        ),
    ]
