# Generated by Django 3.2.9 on 2021-11-28 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_post_commenturl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='commentUrl',
        ),
        migrations.AddField(
            model_name='post',
            name='comments',
            field=models.CharField(default='', max_length=512),
        ),
    ]
