# Generated by Django 3.2.9 on 2021-11-28 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20211128_0807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='comments',
            field=models.CharField(max_length=512, null=True),
        ),
    ]
