# Generated by Django 3.2.8 on 2021-10-28 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_delete_newuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='password',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
    ]
