# Generated by Django 3.2.9 on 2021-12-02 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_post_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='inbox',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.author', verbose_name='For author'),
        ),
        migrations.AddField(
            model_name='inbox',
            name='follow',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.following', verbose_name='Related following'),
        ),
        migrations.AddField(
            model_name='inbox',
            name='item_type',
            field=models.CharField(choices=[('post', 'Post'), ('like', 'Like'), ('follow', 'Follow')], default='post', max_length=6, verbose_name='Item type'),
        ),
        migrations.AddField(
            model_name='inbox',
            name='like',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.likepost', verbose_name='Related like'),
        ),
        migrations.AddField(
            model_name='inbox',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.post', verbose_name='Related post'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='contentType',
            field=models.CharField(choices=[('text/markdown', 'Common Mark'), ('text/plain', 'Utf-8'), ('application/base64', 'application/base64'), ('image/png;base64', 'PNG'), ('image/jpeg;base64', 'JPEG')], default='text/plain', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='comments',
            field=models.CharField(default=None, max_length=512, null=True),
        ),
    ]
