# Generated by Django 3.2.9 on 2021-11-24 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20211028_2025'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=128, verbose_name='Admin Username')),
                ('password_md5', models.CharField(max_length=32, verbose_name='Admin Password MD5')),
            ],
        ),
        migrations.AddField(
            model_name='node',
            name='create_time',
            field=models.FloatField(default=1637774092.6524081, verbose_name='Node create timestamp'),
        ),
        migrations.AddField(
            model_name='node',
            name='host',
            field=models.CharField(default='http://127.0.0.1:8000', max_length=512, verbose_name='Host URL'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='node',
            name='http_username',
            field=models.CharField(blank=True, default='', max_length=512, null=True, verbose_name='Http Auth Username(FETCH)'),
        ),
        migrations.AddField(
            model_name='node',
            name='if_approved',
            field=models.BooleanField(default=True, verbose_name='If approved to connect'),
        ),
        migrations.AddField(
            model_name='node',
            name='node_type',
            field=models.CharField(choices=[('SHARE', 'Share'), ('FETCH', 'Fetch')], default='SHARE', max_length=5, verbose_name='Node Type'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='node',
            name='password_md5',
            field=models.CharField(default='a66abb5684c45962d887564f08346e8d', max_length=32, verbose_name='Auth Password'),
            preserve_default=False,
        ),
    ]
