# Generated by Django 3.2.9 on 2021-11-06 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20211028_2025'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='profilePic',
            new_name='profileImage',
        ),
    ]
