# Generated by Django 3.2.9 on 2021-11-07 20:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Following',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followee', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='followee_set', to=settings.AUTH_USER_MODEL)),
                ('follower', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='follower_set', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
