# Generated by Django 3.2.9 on 2021-11-07 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_following'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admin',
            options={},
        ),
        migrations.AlterModelOptions(
            name='author',
            options={},
        ),
        migrations.AlterModelManagers(
            name='admin',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='author',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='author',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='author',
            name='email',
        ),
        migrations.RemoveField(
            model_name='author',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='author',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='author',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='author',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='author',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='author',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='author',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='author',
            name='username',
        ),
    ]
