# Generated by Django 3.2.9 on 2021-11-07 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20211107_2034'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='following',
            unique_together={('follower', 'followee')},
        ),
    ]
