# Generated by Django 3.2.9 on 2021-11-07 23:23

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_following_unique_together'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='following',
            constraint=models.CheckConstraint(check=models.Q(('follower', django.db.models.expressions.F('followee')), _negated=True), name='follower_ne_followee'),
        ),
    ]
