# Generated by Django 3.2.9 on 2021-11-10 02:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_following_follower_ne_followee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='authorId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
