# Generated by Django 3.2.9 on 2021-11-10 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_alter_post_authorid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post_text',
            new_name='content',
        ),
    ]
