# Generated by Django 3.2.9 on 2021-11-12 04:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_rename_post_text_post_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='authorId',
            new_name='author',
        ),
        migrations.AlterField(
            model_name='following',
            name='followee',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='follower_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='following',
            name='follower',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='followed_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
