# Generated by Django 3.2.9 on 2021-11-24 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_auto_20211124_0255'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='uid',
            new_name='id',
        ),
    ]
